title: "NAIL: Neurosymbolic AI Library"
description: The Neurosymbolic AI Library (NAIL) is a toolkit for designing modular hybrid gradient-based and symbol-based AI systems that are sample-efficient and extensible.
show_downloads: true
google_analytics: G-S8Q1KT3DGX
theme: jekyll-theme-cayman